# cribbed from https://github.com/robhinds/robhinds.github.io
# Site settings
title: Sean Summers
twitter_username: seansummers
name: Sean Summers

# Build settings
markdown: kramdown

#User specific content
# intro
intro: |
    Hello, world!

#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/seansummers
 - title: StackOverflow
   url: http://stackoverflow.com/users/650756/sean-summers
 - title: DZone
   url: https://dzone.com/users/1118933/seansummers.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/sean-summers-b75019a

#Any buzzword skills you want to include
skills:
 - Python / Jython
 - linux
 - Cognos TM1
 - SQL
 - AWS

#Work experience is required
roles:
 - title: Senior Systems Administrator
   start: 2015
   end: Ongoing
   employer: Hesburgh Libraries, University of Notre Dame
   description: Working towards a CloudFirst posture.
 - title: Systems Analyst II
   start: 2011
   end: 2015
   employer: United Vision Logistics
   description: Designed and managed Cognos TM1 deployment, business record DMS, and internal-facing financial and business reporting services.
 - title: Data Logistician
   start: 2008
   end: Ongoing
   employer: IAmIndependent.com
   description: For hire consultant, specializing in big data analytics and cloud deployment.

#Education is required
education:
 - level: 130+ undergraduate credits
   date: 1992
   subject: dual degree program, Mathematics and Philosophy
   school: Schreiner University

#List of interesting Github repo/projects to include - optional
github:
 - seansummers/python-cac

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/650756/sean-summers
   flairimageurl: http://stackoverflow.com/users/flair/650756.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Linux</strong>: I am experienced in a variety of linux distributions.
   <br/><br/>
   <strong>CEHv8</strong>: I am a Certified Ethical Hacker (v8)
  
